# Generated by Django 5.2.4 on 2025-07-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_alter_user_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='active',
            field=models.CharField(choices=[('inactive', 'Inactive app'), ('active', 'Active app')], default='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('hobby', 'Hobby plan'), ('pro', 'Pro plan')], default='hobby'),
        ),
    ]
